apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-bundle-overridingyrgb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-bundle-overridingyrgb
    app.kubernetes.io/part-of: test-app-ymhr
  name: build-suite-test-bundle-overridingyrgb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-suite-test-bundle-overridingyrgb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-suite-test-bundle-overridingyrgb
    spec:
      containers:
      - image: quay.io/susdas/test-im
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
